### ISSUE TITLE
Unlimited water travel

### ISSUE THREAD

**Issue by StevenZabolotny** [Bouowmx/best-project-2015#7]
Since the distance is now measured off of the route, you can travel in water where google maps tries to find the nearest route and finds it to be a very short distance. This makes water travel nearly unlimited and much easier than land travel, which is a pretty big bug. The only solution I can think of is preventing players from moving onto water.

**Comment by alb-yeung** [comment]
I don't think it's THAT big a problem as getting back on land after leaving the water still requires you to drive across the bridges except on the places where piers are at. If you really wanted to, you could think of it as stealing a boat, which is usually faster than driving.

**Comment by RzhanRichardZhan** [comment]
Almost done.
I used CORS and some canvas HTML5 stuff to detect blue pixels on the google maps
Albert will finish it by actually implementing it

**Comment by RzhanRichardZhan** [comment]
Fixed. But new issue
